import { Ionicons } from '@expo/vector-icons';
import React, { useMemo, useState } from 'react';
import { Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View, useWindowDimensions } from 'react-native';

const logo = require('../../assets/iron-fit-core-official-lockup.webp');

type ModuleKey = 'overview'|'students'|'team'|'assessments'|'equipment'|'exercises'|'workouts'|'schedule'|'access'|'financial'|'billing'|'intelligence'|'integrations'|'settings'|'security';

const nav: Array<[ModuleKey,string,any,string?]> = [
 ['overview','Cockpit','grid-outline'],['students','Alunos','people-outline'],['team','Equipe','people-circle-outline'],
 ['assessments','Avaliações','pulse-outline'],['equipment','Equipamentos','barbell-outline'],['exercises','Exercícios','fitness-outline'],
 ['workouts','Treinos','clipboard-outline'],['schedule','Agenda','calendar-outline'],['access','Acessos','key-outline'],
 ['financial','Financeiro','wallet-outline','ADM'],['billing','Plano IRON','card-outline','OWNER'],
 ['intelligence','Iron Intelligence','sparkles-outline'],['integrations','Integrações','git-network-outline','OWNER'],
 ['settings','Configurações','options-outline','ADM'],['security','Segurança','shield-checkmark-outline','ADM']
];

const pages: Record<ModuleKey,{eyebrow:string;title:string;lead:string;stats:Array<[string,string,string]>}> = {
 overview:{eyebrow:'COMMAND CENTER',title:'Cockpit operacional',lead:'A academia inteira em contexto — operação, pessoas, receita e inteligência no mesmo centro de decisão.',stats:[['248','Alunos ativos','+6,8%'],['87','Check-ins hoje','agora'],['92%','Ocupação de pico','18h–20h'],['94%','Adimplência','estável']]},
 students:{eyebrow:'GESTÃO DE ALUNOS',title:'Alunos',lead:'Cadastro, jornada, situação, consentimentos e relacionamento em uma superfície operacional única.',stats:[['248','Ativos','+18 mês'],['8','Pendências','atenção'],['31','Avaliações','30 dias'],['12','Aniversários','mês']]},
 team:{eyebrow:'PESSOAS & RBAC',title:'Equipe',lead:'Profissionais, papéis e responsabilidades respeitando o contexto autorizado da academia.',stats:[['14','Profissionais','ativos'],['9','Treinadores','staff'],['3','Recepção','staff'],['2','Gestores','admin']]},
 assessments:{eyebrow:'EVOLUÇÃO',title:'Avaliações',lead:'Evolução física e contexto profissional conectados à prescrição e ao acompanhamento.',stats:[['31','Recentes','30 dias'],['9','Hoje','agenda'],['4','Reavaliações','pendentes'],['96%','Completas','qualidade']]},
 equipment:{eyebrow:'INVENTÁRIO INTELIGENTE',title:'Equipamentos',lead:'Inventário da academia conectado ao catálogo canônico, exercícios e capacidade de treino.',stats:[['126','Inventariados','total'],['118','Disponíveis','93,6%'],['5','Manutenção','planejada'],['3','Indisponíveis','atenção']]},
 exercises:{eyebrow:'BIBLIOTECA DE MOVIMENTO',title:'Exercícios',lead:'Exercícios e capacidades relacionados aos equipamentos disponíveis e ao contexto de treino.',stats:[['342','Catalogados','biblioteca'],['126','Com equipamento','mapeados'],['54','Peso livre','categoria'],['22','Mobilidade','categoria']]},
 workouts:{eyebrow:'PRESCRIÇÃO',title:'Treinos',lead:'Prescrição, acompanhamento e revisão profissional, incluindo candidatos inteligentes sob controle humano.',stats:[['186','Ativos','agora'],['42','Atualizados','semana'],['7','Em revisão','humana'],['96%','Acompanhados','cobertura']]},
 schedule:{eyebrow:'OPERAÇÃO EM TEMPO REAL',title:'Agenda',lead:'Aulas, horários, reservas, capacidade e presença conectados à operação da academia.',stats:[['34','Aulas hoje','grade'],['286','Reservas','hoje'],['87','Check-ins','agora'],['92%','Ocupação','pico']]},
 access:{eyebrow:'PRESENÇA & CONTROLE',title:'Acessos',lead:'Entrada, credenciais e histórico no contexto correto da academia e da unidade.',stats:[['87','Entradas hoje','agora'],['4','Alertas','revisar'],['99,7%','Disponibilidade','24h'],['2','Credenciais','novas']]},
 financial:{eyebrow:'FINANCEIRO DA ACADEMIA',title:'Financeiro',lead:'Receita, cobranças dos alunos, pendências e conciliação operacional. Separado do billing SaaS da FM.',stats:[['R$ 42,8 mil','Receita mensal','mês'],['R$ 3,2 mil','A receber','aberto'],['94%','Adimplência','mês'],['R$ 8,6 mil','Previsto','7 dias']]},
 billing:{eyebrow:'ASSINATURA IRON',title:'Plano & assinatura',lead:'Trial, assinatura SaaS, cobrança e entitlement do tenant — domínio separado do financeiro da academia.',stats:[['PRO','Plano atual','ativo'],['24 dias','Ciclo','renovação'],['Ativo','Entitlement','ok'],['Automática','Recorrência','provider']]},
 intelligence:{eyebrow:'IRON INTELLIGENCE',title:'Inteligência governada',lead:'Insights e apoio à decisão com contexto, guardrails e controle humano sobre decisões profissionais.',stats:[['4','Insights','hoje'],['7','Treinos candidatos','revisão'],['0','Críticos','agora'],['Humano','Controle','obrigatório']]},
 integrations:{eyebrow:'ECOSSISTEMA',title:'Integrações',lead:'Providers e conectores governados, com segredos mascarados, OAuth e step-up nas operações sensíveis.',stats:[['4','Disponíveis','catálogo'],['2','Conectadas','ativas'],['0','Falhas','24h'],['Vault','Segredos','protegidos']]},
 settings:{eyebrow:'GOVERNANÇA DO TENANT',title:'Configurações',lead:'Academia, unidade, políticas de experiência, permissões e preferências dentro da autoridade do tenant.',stats:[['1','Academia','tenant'],['2','Unidades','ativas'],['5','Papéis','RBAC'],['12','Políticas','configuradas']]},
 security:{eyebrow:'SEGURANÇA & CONFIANÇA',title:'Segurança',lead:'Autenticação, sessão, MFA, step-up, rastreabilidade e proteção das operações sensíveis.',stats:[['Ativo','MFA','disponível'],['Protegido','Step-up','admin'],['Seguro','Sessão','ativa'],['0','Alertas críticos','24h']]}
};

const rows: Partial<Record<ModuleKey,Array<[string,string,string]>>> = {
 students:[['Marina Costa','Plano Pro · avaliação em dia','Ativa'],['Lucas Almeida','Plano Fit · treino B','Ativo'],['Carla Souza','Mensalidade em aberto','Pendência'],['Rafael Lima','Plano Start · novo aluno','Ativo']],
 team:[['Ana Martins','Treinadora · prescrição','Em atendimento'],['Bruno Reis','Recepção · acesso','Online'],['Diego Alves','Treinador · avaliações','Livre'],['Paula Melo','Gestora · administrativo','Online']],
 assessments:[['Marina Costa','Composição corporal · hoje','Concluída'],['Lucas Almeida','Reavaliação · 14:30','Agendada'],['Carla Souza','Mobilidade · amanhã','Agendada'],['Rafael Lima','Avaliação inicial · 18:00','Pendente']],
 equipment:[['Esteira T-08','Cardio · catálogo IRON','Disponível'],['Leg Press 45','Musculação · manutenção','Manutenção'],['Bike B-12','Cardio · catálogo IRON','Disponível'],['Crossover C-04','Musculação · catálogo IRON','Disponível']],
 exercises:[['Agachamento livre','Força · peso livre','Publicado'],['Remada baixa','Costas · cabo','Publicado'],['Leg press 45°','Pernas · máquina','Publicado'],['Mobilidade torácica','Mobilidade · livre','Publicado']],
 workouts:[['Hipertrofia A','42 alunos · revisão profissional','Atualizado'],['Condicionamento','31 alunos · progressão','Ativo'],['Força Base','27 alunos · candidato IA','Revisão'],['Mobilidade','18 alunos · biblioteca','Ativo']],
 access:[['Marina Costa','Catraca principal','08:42'],['Lucas Almeida','Catraca principal','08:37'],['Ana Martins','Área staff','08:31'],['Rafael Lima','Catraca principal','08:18']],
 financial:[['Mensalidades','R$ 31.420','Recebido'],['Planos anuais','R$ 8.930','Recebido'],['Pendências','R$ 3.240','A receber'],['Projeção 7 dias','R$ 8.610','Previsto']]
};

function CoreMark({compact=false}:{compact?:boolean}) {
 return <View style={[s.coreMark,compact&&s.coreMarkCompact]}>
   <View style={[s.orbit,s.orbitOne]}/><View style={[s.orbit,s.orbitTwo]}/>
   <Image source={logo} resizeMode="contain" style={[s.coreLogo,compact&&s.coreLogoCompact]} accessibilityLabel="IRON FIT CORE"/>
 </View>;
}

function Pill({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'green'|'amber'}) {
 return <View style={[s.pill,tone==='green'&&s.pillGreen,tone==='amber'&&s.pillAmber]}><Text style={s.pillText}>{children}</Text></View>;
}

function AdminGate({kind,onEnter}:{kind:'financial'|'billing'|'integrations'|'settings'|'security';onEnter:()=>void}) {
 const ownerOnly=kind==='billing'||kind==='integrations';
 return <View style={s.gate}>
   <View style={s.gateIcon}><Ionicons name="lock-closed-outline" size={25} color="#67d6ff"/></View>
   <Text style={s.cardEyebrow}>SUPERFÍCIE PROTEGIDA</Text>
   <Text style={s.gateTitle}>{ownerOnly?'Acesso de Proprietário':'Acesso administrativo'} necessário</Text>
   <Text style={s.cardText}>Este preview simula a barreira de autorização. Na aplicação real, RBAC, tenant, entitlement e step-up permanecem autoridade do backend. Nenhuma proteção é implementada apenas escondendo controles.</Text>
   <TouchableOpacity onPress={onEnter} style={s.primaryButton}><Ionicons name="shield-checkmark-outline" size={17} color="#03101d"/><Text style={s.primaryButtonText}>Simular autorização protegida</Text></TouchableOpacity>
 </View>;
}

function IntelligenceCard({selected}:{selected:string}) {
 return <View style={s.intelCard}><View style={s.intelHead}><View><Text style={s.cardEyebrow}>CORE INTELLIGENCE</Text><Text style={s.cardTitle}>Leitura contextual</Text></View><Ionicons name="sparkles-outline" size={20} color="#67d6ff"/></View>
   <Text style={s.cardText}>{selected||'Operação dentro do padrão. O Core prioriza exceções e mantém decisões profissionais sob controle humano.'}</Text>
   <View style={s.aiFoot}><View style={s.liveDot}/><Text style={s.aiFootText}>Insight demonstrativo · dados locais · sem decisão automática</Text></View>
 </View>;
}

function Schedule({setSelected}:{setSelected:(v:string)=>void}) {
 return <View style={s.grid}><View style={[s.card,s.flexWide]}><Text style={s.cardEyebrow}>AGENDA DE HOJE</Text><Text style={s.cardTitle}>Aulas & capacidade</Text>
 {([['07:00','Funcional','18 / 20'],['09:00','Pilates','12 / 14'],['18:30','Spinning','24 / 24'],['20:00','Cross Training','16 / 20']] as const).map(x=>
 <TouchableOpacity key={x[0]} onPress={()=>setSelected(`${x[1]} · ${x[0]} · ${x[2]} reservas`)} style={s.dataRow}><View style={s.time}><Text style={s.timeText}>{x[0]}</Text></View><View style={s.rowCopy}><Text style={s.rowTitle}>{x[1]}</Text><Text style={s.rowSub}>Sala principal · instrutor confirmado</Text></View><Pill tone={x[2]==='24 / 24'?'amber':'blue'}>{x[2]}</Pill></TouchableOpacity>)}
 </View><View style={s.card}><Text style={s.cardEyebrow}>CAPACIDADE</Text><Text style={s.cardTitle}>Próximas horas</Text><Text style={s.heroNumber}>92%</Text><Text style={s.muted}>ocupação projetada no pico</Text><View style={s.meter}><View style={[s.meterFill,{width:'92%'}]}/></View><Text style={s.cardText}>Pico entre 18h e 20h. A operação ainda está dentro da capacidade configurada.</Text></View></View>;
}

function IntegrationGrid({setSelected}:{setSelected:(v:string)=>void}) {
 const list=[['card-outline','Pagamentos','Conectado'],['finger-print-outline','Controle de acesso','Conectado'],['chatbubbles-outline','Mensageria','Disponível'],['analytics-outline','Analytics','Disponível'],['fitness-outline','Aggregator Hub','Preparado'],['cloud-outline','OAuth providers','Governado']];
 return <View style={s.connectorGrid}>{list.map(x=><TouchableOpacity key={x[1]} onPress={()=>setSelected(`${x[1]} · ${x[2]}`)} style={s.connector}><View style={s.connectorIcon}><Ionicons name={x[0] as any} size={21} color="#67d6ff"/></View><View style={s.rowCopy}><Text style={s.rowTitle}>{x[1]}</Text><Text style={s.rowSub}>Conector governado pelo IRON</Text></View><Pill tone={x[2]==='Conectado'?'green':'blue'}>{x[2]}</Pill></TouchableOpacity>)}</View>;
}

function Workspace({active,selected,setSelected}:{active:ModuleKey;selected:string;setSelected:(v:string)=>void}) {
 if(active==='overview') return <View style={s.grid}><View style={[s.card,s.flexWide]}><View style={s.cardHeader}><View><Text style={s.cardEyebrow}>PULSO DA OPERAÇÃO</Text><Text style={s.cardTitle}>Agora na academia</Text></View><Pill tone="green">OPERAÇÃO SAUDÁVEL</Pill></View>
 {['Fluxo de alunos dentro do esperado','Agenda com alta ocupação no pico','Nenhum incidente crítico','Cobranças reconciliadas'].map((x,i)=><TouchableOpacity key={x} onPress={()=>setSelected(x)} style={s.dataRow}><View style={s.statusIcon}><Ionicons name={i===1?'calendar-outline':i===3?'wallet-outline':'checkmark'} size={15} color="#9ee37d"/></View><View style={s.rowCopy}><Text style={s.rowTitle}>{x}</Text><Text style={s.rowSub}>{i===0?'87 check-ins hoje':i===1?'18h–20h · monitorar capacidade':i===2?'Últimas 24 horas':'Última atualização há 4 min'}</Text></View><Ionicons name="chevron-forward" size={15} color="#50677f"/></TouchableOpacity>)}
 </View><View style={s.corePanel}><CoreMark/><Text style={s.corePanelTitle}>Inteligência no centro.</Text><Text style={s.corePanelText}>Contexto operacional conectado sem substituir a autoridade humana.</Text></View></View>;
 if(active==='schedule') return <Schedule setSelected={setSelected}/>;
 if(active==='integrations') return <><IntegrationGrid setSelected={setSelected}/><IntelligenceCard selected={selected}/></>;
 if(active==='intelligence') return <View style={s.grid}><View style={[s.corePanel,s.flexWide]}><CoreMark/><Text style={s.corePanelTitle}>Core + contexto</Text><Text style={s.corePanelText}>Operação · treino · risco · evolução. A inteligência apoia; o profissional decide.</Text></View><IntelligenceCard selected={selected}/></View>;
 if(active==='billing') return <View style={s.grid}><View style={[s.card,s.flexWide]}><Text style={s.cardEyebrow}>BILLING SaaS · FM TECNOLOGIA</Text><Text style={s.cardTitle}>Assinatura da academia</Text>{[['Plano','IRON Pro'],['Status','Ativo'],['Próxima renovação','22/10/2026'],['Entitlement','Liberado']].map(x=><View key={x[0]} style={s.infoRow}><Text style={s.muted}>{x[0]}</Text><Text style={s.infoValue}>{x[1]}</Text></View>)}</View><IntelligenceCard selected="Este domínio controla a assinatura SaaS do tenant e não se confunde com mensalidades dos alunos."/></View>;
 if(active==='security') return <View style={s.grid}><View style={[s.card,s.flexWide]}><Text style={s.cardEyebrow}>CONTROLES</Text><Text style={s.cardTitle}>Proteção da conta</Text>{[['shield-checkmark-outline','MFA','Disponível'],['key-outline','Step-up administrativo','Protegido'],['timer-outline','Sessão','Segura'],['document-lock-outline','Auditoria','Ativa']].map(x=><View key={x[1]} style={s.dataRow}><View style={s.statusIconBlue}><Ionicons name={x[0] as any} size={16} color="#67d6ff"/></View><View style={s.rowCopy}><Text style={s.rowTitle}>{x[1]}</Text><Text style={s.rowSub}>Controle governado pelo backend</Text></View><Pill tone="green">{x[2]}</Pill></View>)}</View><IntelligenceCard selected="Nenhum evento crítico exige ação neste cenário demonstrativo."/></View>;
 if(active==='settings') return <View style={s.grid}><View style={[s.card,s.flexWide]}><Text style={s.cardEyebrow}>TENANT & UNIDADE</Text><Text style={s.cardTitle}>Contexto operacional</Text>{[['Academia','IRON Academia Demo'],['Unidade ativa','Praia Grande'],['Política de treino','Revisão profissional'],['Experiência do aluno','Aplicativo + Web']].map(x=><TouchableOpacity key={x[0]} onPress={()=>setSelected(`${x[0]} · ${x[1]}`)} style={s.infoRow}><Text style={s.muted}>{x[0]}</Text><Text style={s.infoValue}>{x[1]}</Text></TouchableOpacity>)}</View><IntelligenceCard selected={selected}/></View>;
 const list=rows[active]||[];
 return <View style={s.grid}><View style={[s.card,s.flexWide]}><View style={s.cardHeader}><View><Text style={s.cardEyebrow}>OPERAÇÃO</Text><Text style={s.cardTitle}>Registros recentes</Text></View><View style={s.search}><Ionicons name="search-outline" size={15} color="#71879e"/><TextInput placeholder="Buscar" placeholderTextColor="#71879e" style={s.searchInput} onChangeText={v=>setSelected(v?`Busca local: ${v}`:'')}/></View></View>
 {list.length?list.map(x=><TouchableOpacity key={x[0]} onPress={()=>setSelected(`${x[0]} · ${x[1]} · ${x[2]}`)} style={s.dataRow}><View style={s.avatar}><Text style={s.avatarText}>{x[0].slice(0,2).toUpperCase()}</Text></View><View style={s.rowCopy}><Text style={s.rowTitle}>{x[0]}</Text><Text style={s.rowSub}>{x[1]}</Text></View><Pill tone={x[2].includes('Pend')||x[2].includes('Manutenção')?'amber':'blue'}>{x[2]}</Pill></TouchableOpacity>):<Text style={s.cardText}>Superfície demonstrativa preparada para o domínio canônico.</Text>}
 </View><IntelligenceCard selected={selected}/></View>;
}

export function PremiumDemoApp(){
 const {width}=useWindowDimensions(); const mobile=width<820; const [active,setActive]=useState<ModuleKey>('overview'); const [selected,setSelected]=useState(''); const [unlocked,setUnlocked]=useState<Record<string,boolean>>({});
 const page=useMemo(()=>pages[active],[active]); const protectedArea=['financial','billing','integrations','settings','security'].includes(active); const canView=!protectedArea||unlocked[active];
 const change=(key:ModuleKey)=>{setActive(key);setSelected('')};
 return <View style={s.app}>
  <View style={[s.top,mobile&&s.topMobile]}><View style={s.brandBlock}><Image source={logo} resizeMode="contain" style={s.headerLogo}/><View style={s.brandCopy}><Text style={s.tag}>Inteligência no centro. Evolução em movimento.</Text><Text style={s.by}>BY FM TECNOLOGIA</Text></View></View><View style={s.topActions}><Pill tone="green">● OPERAÇÃO ONLINE</Pill><View style={s.demo}><View style={s.liveDot}/><Text style={s.demoText}>PREVIEW · DADOS DEMONSTRATIVOS</Text></View></View></View>
  <View style={[s.shell,mobile&&s.shellMobile]}>
   <View style={[s.navFrame,mobile&&s.navFrameMobile]}><ScrollView horizontal={mobile} showsHorizontalScrollIndicator={false} contentContainerStyle={mobile?s.navRow:s.navColumn}>
    {!mobile&&<View style={s.navBrand}><CoreMark compact/><Text style={s.navBrandText}>CENTRAL OPERACIONAL</Text></View>}
    {nav.map(([key,label,icon,role])=><TouchableOpacity key={key} onPress={()=>change(key)} style={[s.navItem,active===key&&s.navActive]}><Ionicons name={icon} size={18} color={active===key?'#67d6ff':'#71879e'}/><Text style={[s.navText,active===key&&s.navTextActive]}>{label}</Text>{role&&<Text style={s.roleTag}>{role}</Text>}</TouchableOpacity>)}
   </ScrollView></View>
   <ScrollView style={s.content} contentContainerStyle={[s.inner,mobile&&s.innerMobile]}>
    <View style={s.pageHead}><View style={s.pageCopy}><Text style={s.eyebrow}>{page.eyebrow}</Text><Text style={[s.title,mobile&&s.titleMobile]}>{page.title}</Text><Text style={s.lead}>{page.lead}</Text></View><View style={s.context}><Ionicons name="business-outline" size={15} color="#67d6ff"/><View><Text style={s.contextTop}>IRON ACADEMIA DEMO</Text><Text style={s.contextSub}>Unidade Praia Grande</Text></View></View></View>
    {!canView?<AdminGate kind={active as any} onEnter={()=>setUnlocked(v=>({...v,[active]:true}))}/>:<>
     <View style={[s.stats,mobile&&s.statsMobile]}>{page.stats.map(x=><TouchableOpacity key={x[1]} onPress={()=>setSelected(`${x[1]} · ${x[0]}`)} style={s.stat}><View style={s.statTop}><Text style={s.statValue}>{x[0]}</Text><Text style={s.statTrend}>{x[2]}</Text></View><Text style={s.statLabel}>{x[1]}</Text><View style={s.statLine}/></TouchableOpacity>)}</View>
     <Workspace active={active} selected={selected} setSelected={setSelected}/>
    </>}
   </ScrollView>
  </View>
 </View>
}

const s=StyleSheet.create({
 app:{flex:1,backgroundColor:'#050b14'},top:{minHeight:104,paddingHorizontal:26,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'rgba(103,214,255,.12)',backgroundColor:'#040c18',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},topMobile:{minHeight:92,paddingHorizontal:14},brandBlock:{flexDirection:'row',alignItems:'center',gap:16},headerLogo:{width:170,height:72,filter:'hue-rotate(105deg) saturate(1.15)' as any},brandCopy:{borderLeftWidth:1,borderLeftColor:'rgba(103,214,255,.14)',paddingLeft:16},tag:{color:'#dce9f6',fontSize:12,fontWeight:'700'},by:{color:'#667d96',fontSize:9,fontWeight:'900',letterSpacing:1.7,marginTop:5},topActions:{flexDirection:'row',alignItems:'center',gap:9,flexWrap:'wrap',justifyContent:'flex-end'},demo:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,paddingVertical:7,borderWidth:1,borderColor:'rgba(103,214,255,.16)',borderRadius:999,backgroundColor:'#071629'},demoText:{color:'#9fcdf6',fontSize:8,fontWeight:'900',letterSpacing:.7},liveDot:{width:6,height:6,borderRadius:6,backgroundColor:'#67d6ff'},
 shell:{flex:1,flexDirection:'row'},shellMobile:{flexDirection:'column'},navFrame:{width:258,minWidth:258,maxWidth:258,flexShrink:0,backgroundColor:'#040c18',borderRightWidth:1,borderRightColor:'rgba(103,214,255,.09)'},navFrameMobile:{width:'100%',minWidth:0,maxWidth:'100%',height:62,borderRightWidth:0,borderBottomWidth:1,borderBottomColor:'rgba(103,214,255,.09)'},navColumn:{padding:14,paddingBottom:26},navRow:{paddingHorizontal:7,alignItems:'center'},navBrand:{height:110,alignItems:'center',justifyContent:'center',marginBottom:8,borderBottomWidth:1,borderBottomColor:'rgba(103,214,255,.08)'},navBrandText:{color:'#667d96',fontSize:8,fontWeight:'900',letterSpacing:1.6,marginTop:4},navItem:{minHeight:44,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:12,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:'transparent',marginVertical:2},navActive:{backgroundColor:'#081c31',borderColor:'rgba(47,145,255,.32)'},navText:{flexShrink:1,color:'#8fa2b6',fontSize:12,fontWeight:'700'},navTextActive:{color:'#eef6ff'},roleTag:{marginLeft:'auto',color:'#67d6ff',fontSize:7,fontWeight:'900',letterSpacing:.7},
 content:{flex:1,minWidth:0},inner:{width:'100%',maxWidth:1320,alignSelf:'center',padding:30,paddingBottom:60},innerMobile:{padding:16,paddingBottom:40},pageHead:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:20,flexWrap:'wrap'},pageCopy:{flex:1,minWidth:280},eyebrow:{color:'#2f91ff',fontSize:9,fontWeight:'900',letterSpacing:1.7},title:{color:'#f4f9ff',fontSize:40,fontWeight:'900',letterSpacing:-1.5,marginTop:9},titleMobile:{fontSize:31},lead:{color:'#9aadc1',fontSize:14,lineHeight:22,marginTop:6,maxWidth:720},context:{flexDirection:'row',alignItems:'center',gap:10,padding:11,borderWidth:1,borderColor:'rgba(103,214,255,.11)',borderRadius:14,backgroundColor:'#071426'},contextTop:{color:'#dce9f6',fontSize:10,fontWeight:'900'},contextSub:{color:'#71879e',fontSize:9,marginTop:2},
 stats:{flexDirection:'row',gap:12,marginTop:24},statsMobile:{flexWrap:'wrap'},stat:{flex:1,minWidth:150,padding:16,borderWidth:1,borderColor:'rgba(47,145,255,.11)',borderRadius:18,backgroundColor:'#071528'},statTop:{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between',gap:8},statValue:{color:'#f4f9ff',fontSize:22,fontWeight:'900'},statTrend:{color:'#67d6ff',fontSize:8,fontWeight:'800'},statLabel:{color:'#8397ad',fontSize:10,marginTop:5},statLine:{width:'34%',height:2,borderRadius:2,backgroundColor:'#2f91ff',marginTop:13},
 grid:{flexDirection:'row',gap:14,marginTop:14,flexWrap:'wrap'},flexWide:{flex:1.45},card:{flex:1,minWidth:300,padding:20,borderWidth:1,borderColor:'rgba(47,145,255,.11)',borderRadius:20,backgroundColor:'#071528'},cardHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,flexWrap:'wrap'},cardEyebrow:{color:'#2f91ff',fontSize:8,fontWeight:'900',letterSpacing:1.4},cardTitle:{color:'#eef6ff',fontSize:18,fontWeight:'900',letterSpacing:-.25,marginTop:5},cardText:{color:'#8fa3b8',fontSize:12,lineHeight:19,marginTop:13},dataRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:11,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.045)'},rowCopy:{flex:1,minWidth:100},rowTitle:{color:'#dce9f6',fontSize:12,fontWeight:'800'},rowSub:{color:'#71879e',fontSize:9,marginTop:3},avatar:{width:36,height:36,borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:'#091a2f',borderWidth:1,borderColor:'rgba(47,145,255,.13)'},avatarText:{color:'#67d6ff',fontSize:9,fontWeight:'900'},statusIcon:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(158,227,125,.07)'},statusIconBlue:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(47,145,255,.09)'},time:{width:54,paddingVertical:7,alignItems:'center',borderRadius:10,backgroundColor:'#091a2f'},timeText:{color:'#67d6ff',fontSize:10,fontWeight:'900'},
 pill:{paddingHorizontal:8,paddingVertical:5,borderRadius:999,backgroundColor:'rgba(47,145,255,.09)',borderWidth:1,borderColor:'rgba(47,145,255,.14)'},pillGreen:{backgroundColor:'rgba(158,227,125,.07)',borderColor:'rgba(158,227,125,.12)'},pillAmber:{backgroundColor:'rgba(251,191,36,.07)',borderColor:'rgba(251,191,36,.14)'},pillText:{color:'#b9dcff',fontSize:8,fontWeight:'900'},muted:{color:'#71879e',fontSize:10},heroNumber:{color:'#f4f9ff',fontSize:40,fontWeight:'900',marginTop:24},meter:{height:5,borderRadius:5,backgroundColor:'#0c2138',marginTop:16,overflow:'hidden'},meterFill:{height:5,borderRadius:5,backgroundColor:'#2f91ff'},
 corePanel:{flex:1,minWidth:300,minHeight:300,padding:22,borderWidth:1,borderColor:'rgba(47,145,255,.14)',borderRadius:24,backgroundColor:'#061325',alignItems:'center',justifyContent:'center',overflow:'hidden'},corePanelTitle:{color:'#eef6ff',fontSize:17,fontWeight:'900',marginTop:2},corePanelText:{color:'#7f94aa',fontSize:11,lineHeight:17,textAlign:'center',maxWidth:330,marginTop:6},coreMark:{width:220,height:150,alignItems:'center',justifyContent:'center'},coreMarkCompact:{width:145,height:70},coreLogo:{width:170,height:100,zIndex:3,filter:'hue-rotate(105deg) saturate(1.15)' as any},coreLogoCompact:{width:110,height:62},orbit:{position:'absolute',borderWidth:1,borderColor:'rgba(47,145,255,.16)',borderRadius:999},orbitOne:{width:130,height:130},orbitTwo:{width:180,height:180,borderStyle:'dashed',opacity:.6},
 intelCard:{flex:1,minWidth:300,marginTop:14,padding:20,borderWidth:1,borderColor:'rgba(47,145,255,.13)',borderRadius:20,backgroundColor:'#061325'},intelHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},aiFoot:{flexDirection:'row',alignItems:'center',gap:7,marginTop:18,paddingTop:12,borderTopWidth:1,borderTopColor:'rgba(103,214,255,.08)'},aiFootText:{color:'#667d96',fontSize:8,fontWeight:'700'},
 connectorGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:14},connector:{width:'31%',minWidth:260,flexGrow:1,flexDirection:'row',alignItems:'center',gap:11,padding:17,borderWidth:1,borderColor:'rgba(47,145,255,.11)',borderRadius:18,backgroundColor:'#071528'},connectorIcon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#091a2f'},
 search:{width:210,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10,borderWidth:1,borderColor:'rgba(47,145,255,.12)',borderRadius:11,backgroundColor:'#050f1d'},searchInput:{flex:1,color:'#dce9f6',fontSize:10,paddingVertical:8,outlineStyle:'none' as any},infoRow:{minHeight:50,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.045)'},infoValue:{color:'#dce9f6',fontSize:11,fontWeight:'800'},
 gate:{marginTop:25,maxWidth:800,padding:28,borderWidth:1,borderColor:'rgba(47,145,255,.18)',borderRadius:24,backgroundColor:'#061325'},gateIcon:{width:50,height:50,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#091a2f',marginBottom:17},gateTitle:{color:'#f4f9ff',fontSize:24,fontWeight:'900',letterSpacing:-.5,marginTop:6},primaryButton:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:8,marginTop:20,paddingHorizontal:15,paddingVertical:11,borderRadius:11,backgroundColor:'#67d6ff'},primaryButtonText:{color:'#03101d',fontSize:10,fontWeight:'900'}
});